### 1. Scrape the details of most viewed videos on YouTube from Wikipedia:
    url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/

You need to find following details:

- Rank
- Name
- Artist
- Upload date
- Views

In [113]:
#importing all required libraries
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
import time
from bs4 import BeautifulSoup
import requests

In [2]:
#connecting web driver
driver= webdriver. Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')

In [3]:
link= " https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(link)

In [4]:
Rank = []
Name = []
Artist = []
Views = []
Date = []

In [5]:
for i in range(1,31):
    rank=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
    try:
        Rank.append(rank.text)
    except NoSuchElementException:
        Rank.append("-")
        
       
for i in range(1,31):
    name=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
    try:
        Name.append(name.text.strip().split('"')[1]) #appending only the names of the videos
    except NoSuchElementException:
        Name.append("-")
 
for i in range(1,31):
    artist=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
    try:
        Artist.append(artist.text)
    except NoSuchElementException:
        Artist.append("-")
        
for i in range(1,31):
    views=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
    try:
        Views.append(views.text)
    except NoSuchElementException:
        Views.append("-")
        
        
for i in range(1,31):
    date=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")
    try:
        Date.append(date.text)
    except NoSuchElementException:
        Date.append("-")

In [6]:
Top_Youtuube_video=pd.DataFrame({})
Top_Youtuube_video['Rank']=Rank
Top_Youtuube_video['Name']=Name
Top_Youtuube_video['Artist']=Artist
Top_Youtuube_video['Views']=Views
Top_Youtuube_video['Date']=Date
Top_Youtuube_video

,Rank,Name,Artist,Views,Date
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,9.41,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,7.56,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids,5.76,"October 8, 2016"
3,4.,Shape of You,Ed Sheeran,5.47,"January 30, 2017"
4,5.,See You Again,Wiz Khalifa,5.28,"April 6, 2015"
5,6.,Bath Song,Cocomelon – Nursery Rhymes,4.54,"May 2, 2018"
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,4.51,"February 27, 2018"
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,4.46,"January 31, 2012"
8,9.,Uptown Funk,Mark Ronson,4.31,"November 19, 2014"
9,10.,Phonics Song with Two Words,ChuChu TV,4.20,"March 6, 2014"
10,11.,Gangnam Style,Psy,4.20,"July 15, 2012"
11,12.,Dame Tu Cosita,El Chombo,3.62,"April 5, 2018"
12,13.,Sugar,Maroon 5,3.56,"January 14, 2015"
13,14.,Sorry,Justin Bieber,3.47,"October 22, 2015"
14,15.,Roar,Katy Perry,3.44,"September 5, 2013"
15,16.,Counting Stars,OneRepublic,3.41,"May 31, 2013"
16,17.,Thinking Out Loud,Ed Sheeran,3.33,"October 7, 2014"
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,3.28,"May 24, 2018"
18,19.,Dark Horse,Katy Perry,3.15,"February 20, 2014"
19,20.,Faded,Alan Walker,3.15,"December 3, 2015"
20,21.,Girls Like You,Maroon 5,3.14,"May 31, 2018"
21,22.,Lean On,Major Lazer,3.10,"March 22, 2015"
22,23.,Bailando,Enrique Iglesias,3.10,"April 11, 2014"
23,24.,Shake It Off,Taylor Swift,3.10,"August 18, 2014"
24,25.,Let Her Go,Passenger,3.08,"July 25, 2012"
25,26.,Axel F,Crazy Frog,3.02,"June 16, 2009"
26,27.,Mi Gente,J Balvin,2.98,"June 29, 2017"
27,28.,Perfect,Ed Sheeran,2.97,"November 9, 2017"
28,29.,Waka Waka (This Time for Africa),Shakira,2.96,"June 4, 2010"
29,30.,Hello,Adele,2.88,"October 22, 2015"

### 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.

You need to find following details:
* Match title (I.e. 1st ODI)
* Series
* Place
* Date
* Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [69]:
#connecting web driver
driver= webdriver. Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')

In [70]:
link= "https://www.bcci.tv"
driver.get(link)

In [82]:
intr = driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]')
try:
    intr.click() #clicking on International button
except ElementNotInteractableException:
    pass
     
fixtr =  driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')
try: 
    fixtr.click() #clicking on Fixtures button
except ElementNotInteractableException:
    pass

In [85]:
#Will keep scrolling down the webpage until it cannot scroll no more
last_height = driver.execute_script('return document.body.scrollHeight')
while True:
    driver.execute_script('window.scrollTo(0,document.body.scrollHeight)')
    time.sleep(2)
    new_height = driver.execute_script('return document.body.scrollHeight')
    try:
        driver.find_element_by_xpath('/html/body/div[4]/div/div/div[2]/section/button').click()
        time.sleep(2)
    except:
        pass
    if new_height == last_height:
        break
    last_height = new_height

In [86]:
Match = []
Series = []
Place = []
Date = []
Time = []

In [87]:
match = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
series = driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
place = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
date = driver.find_elements_by_xpath("//div[@class='fixture__full-date']")
time = driver.find_elements_by_xpath("//span[@class='fixture__time']")

In [88]:
for m in match:
    try:
        Match.append(m.text)
    except NoSuchElementException:
        Match.append("-")
for s in series:
    try:
        Series.append(s.text)
    except NoSuchElementException:
        Series.append("-")
        
for p in place:
    try:
        Place.append(p.text)
    except NoSuchElementException:
        Place.append("-")
        
for d in date:
    try:
        Date.append(d.text)
    except NoSuchElementException:
        Date.append("-")
for t in time:
    try:
        Time.append(t.text) 
    except NoSuchElementException:
        Time.append("-")

In [89]:
Cricket=pd.DataFrame({})
Cricket['Match']=Match
Cricket['Series']=Series
Cricket['Place']=Place
Cricket['Date']=Date
Cricket['Time']=Time
Cricket

,Match,Series,Place,Date,Time
0,Match 16,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",24\nOCTOBER\n19:30 IST,19:30 IST
1,Match 28,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",31\nOCTOBER\n19:30 IST,19:30 IST
2,Match 33,2021 ICC MEN'S T20 WORLD CUP,"Zayed Cricket Stadium, Abu Dhabi",03\nNOVEMBER\n19:30 IST,19:30 IST
3,Match 37,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",05\nNOVEMBER\n19:30 IST,19:30 IST
4,Match 42,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",08\nNOVEMBER\n19:30 IST,19:30 IST
5,1st T20I,INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",17\nNOVEMBER\n19:00 IST,19:00 IST
6,2nd T20I,INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",19\nNOVEMBER\n19:00 IST,19:00 IST
7,3rd T20I,INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",21\nNOVEMBER\n19:00 IST,19:00 IST
8,1st Test,INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",25\nNOVEMBER\n09:30 IST,09:30 IST
9,2nd Test,INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",03\nDECEMBER\n09:30 IST,09:30 IST
10,1st Test,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",17\nDECEMBER\n13:30 IST,13:30 IST
11,2nd Test,SOUTH AFRICA V INDIA 2021/2022,"Supersport Park, Centurion",26\nDECEMBER\n13:30 IST,13:30 IST
12,3rd Test,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",03\nJANUARY\n13:30 IST,13:30 IST
13,1st ODI,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",11\nJANUARY\n14:00 IST,14:00 IST
14,2nd ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",14\nJANUARY\n14:00 IST,14:00 IST
15,3rd ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",16\nJANUARY\n14:00 IST,14:00 IST
16,1st T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",19\nJANUARY\n19:30 IST,19:30 IST
17,2nd T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",21\nJANUARY\n19:30 IST,19:30 IST
18,3rd T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",23\nJANUARY\n19:30 IST,19:30 IST
19,4th T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",26\nJANUARY\n19:30 IST,19:30 IST

### 3. Scrape the details of selenium exception from https://www.guru99.com

`You need to find following details:`
- A) Name
- B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [90]:
url =  'https://www.guru99.com/'
driver = webdriver. Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [91]:
selenium = driver.find_element_by_xpath('//*[@id="kt-info-box_57c7b9-89"]/a/div[2]/h4')
try:
    selenium.click() #clicking on Selenium button
except ElementNotInteractableException:
    pass

In [92]:
     
tutorial =  driver.find_element_by_xpath('//*[@id="post-193"]/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
try: 
    tutorial.click() #clicking on Exceptions Tutorial button
except ElementNotInteractableException:
    pass

In [93]:
Name=[]
Desc=[]

In [94]:
for i in range(2,43):
    name = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
    try:
        Name.append(name.text)
    except NoSuchElementException:
        Name.append("-")
for i in range(2,43):    
    desc = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")
    try:
        Desc.append(desc.text)
    except NoSuchElementException:
        Desc.append("-")

In [95]:
S_Exception=pd.DataFrame({})
S_Exception['Name']=Name
S_Exception['Description']=Desc
S_Exception

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

## 4.  Scrape the details of State-wise GDP of India from statisticstime.com.

<u>`You have to find following details:`</u>

- A) Rank
- B) State
- C) GSDP at current price (19-20)
- D) GSDP at current price (18-19)
- E) Share(18-19)
- F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [96]:
url =  'http://statisticstimes.com/'
driver = webdriver. Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [97]:
# clicking on Economy and selecting India from dropdown list:-

eco=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button") 
try:
    eco.click()
except ElementNotInteractableException:
    pass

india=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
try:
    india.click()
except ElementNotInteractableException:
    pass

In [98]:
#GDP of Indian states:-

state=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
try:
    state.click()
except ElementNotInteractableException:
    pass

In [99]:
Rank = []
State = []
GSDP19_20 = []
GSDP18_19 = []
Share18_19 = []
GDP = []

In [100]:
for i in range(1,34):
    rank = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
    try:
        Rank.append(rank.text)
    except NoSuchElementException:
        Rank.append("-")
for i in range(1,34):
    state = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
    try:
        State.append(state.text)
    except NoSuchElementException:
        State.append("-")
        
for i in range(1,34):
    gsdp19_20 = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
    try:
        GSDP19_20.append(gsdp19_20.text)
    except NoSuchElementException:
        GSDP19_20.append("-")

for i in range(1,34):
    gsdp18_19 = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
    try:
        GSDP18_19.append(gsdp18_19.text)
    except NoSuchElementException:
        GSDP18_19.append("-")

for i in range(1,34):
    share18_19 = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
    try:
        Share18_19.append(share18_19.text)
    except NoSuchElementException:
        Share18_19.append("-")
for i in range(1,34):
    gdp = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")
    try:
        GDP.append(gdp.text)
    except NoSuchElementException:
        GDP.append("-")

In [101]:
State_GDP=pd.DataFrame({})
State_GDP['Rank']=Rank
State_GDP['State']=State
State_GDP['GSDP at current price (19-20)']=GSDP19_20
State_GDP['GSDP at current price (18-19)']=GSDP18_19
State_GDP['Share(18-19)']=Share18_19
State_GDP['GDP']=GDP
State_GDP

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share(18-19),GDP
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

## 5. Scrape the details of trending repositories on https://github.com/.

<u>`You have to find the following details:`</u>
- A) Repository title
- B) Repository description
- C) Contributors count
- D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [114]:
url =  'https://github.com'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [115]:
explore=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary") #explore button
try:
    explore.click()
except ElementNotInteractableException:
    pass
trending=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")#Trending button
try:
    trending.click()
except ElementNotInteractableException:
    pass

In [116]:
T = []
D = []
C = []
L = []
U = []

In [117]:
title = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [118]:
for r in title:
    try:
        U.append(r.get_attribute("href"))
    except NoSuchElementException:
        U.append("-")

In [119]:
title = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [120]:
for r in title:
    try:
        T.append(r.text)
    except NoSuchElementException:
        T.append("-")

In [121]:
for i in U:
    driver.get(i)
    time.sleep(5)
    try:   
        desc = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        D.append(desc.text)
    except NoSuchElementException:
        D.append('-')
    try:
        count = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")
        C.append(count.text)
    except NoSuchElementException:
        C.append('-')

In [122]:
for i in U:
    driver.get(i)
    time.sleep(5)
    try:
        lng = driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]")
        L.append(lng.text)
    except NoSuchElementException:
        L.append('-')

In [123]:
Github=pd.DataFrame({})
Github['Title']=T
Github['Description']=D
Github['Contributors count']=C
Github['Language Used']=L
Github

,Title,Description,Contributors count,Language Used
0,WorkerLivesMatter / WorkingTime,-,2,-
1,nuxt / framework,The Hybrid Vue(3) Framework.,33,TypeScript
2,goplus / gop,"GoPlus - The Go+ language for engineering, STE...",22,Go
3,KieSun / all-of-frontend,你想知道的前端内容都在这,19,JavaScript
4,AveYo / MediaCreationTool.bat,Universal MCT wrapper script for all Windows 1...,-,Batchfile
5,twbs / icons,Official open source SVG icon library for Boot...,22,HTML
6,trekhleb / javascript-algorithms,📝 Algorithms and data structures implemented i...,143,JavaScript
7,Chakazul / Lenia,Lenia - Mathematical Life Forms,7,Python
8,microsoft / Swin-Transformer,"This is an official implementation for ""Swin T...",6,Python
9,NVlabs / stylegan3,Official PyTorch implementation of StyleGAN3,3,Python
10,sentsin / layui,采用自身模块规范编写的前端 UI 框架，遵循原生 HTML/CSS/JS 的书写形式，极低门...,17,JavaScript
11,electron-userland / electron-builder,A complete solution to package and build a rea...,379,TypeScript
12,3b1b / videos,Code for the manim-generated scenes used in 3b...,4,Python
13,zhanwen / MathModel,研究生数学建模，本科生数学建模、数学建模竞赛优秀论文，数学建模算法，LaTeX论文模板，算法...,2,TeX
14,qiurunze123 / miaosha,⭐⭐⭐⭐秒杀系统设计与实现.互联网工程师进阶与分析🙋🐓,5,Java
15,smartcontractkit / full-blockchain-solidity-co...,"Ultimate Solidity, Blockchain, and Smart Contr...",-,-
16,practical-tutorials / project-based-learning,Curated list of project-based tutorials,91,-
17,LeCoupa / awesome-cheatsheets,👩‍💻👨‍💻 Awesome cheatsheets for popular program...,107,JavaScript
18,thingsboard / thingsboard,"Open-source IoT Platform - Device management, ...",128,Java
19,ascoders / weekly,前端精读周刊。帮你理解最前沿、实用的技术。,53,JavaScript
20,microsoft / playwright,"Node.js library to automate Chromium, Firefox ...",168,JavaScript
21,ddosify / ddosify,"High-performance load testing tool, written in...",4,Go
22,apache / apisix,The Cloud-Native API Gateway,231,Lua
23,CyC2018 / CS-Notes,📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计,231,Java
24,PanJiaChen / vue-element-admin,🎉 A magical vue admin https://panjiachen.githu...,123,Vue

### Q6. Scrape the details of top 100 songs on https://www.billboard.com

`You have to find the following details:`

- A) Song name
- B) Artist name
- C) Last week rank
- D) Peak rank
- E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [165]:
url =  'https://www.billboard.com/'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [167]:
top100=driver.find_element_by_xpath("//*[@id='root']/div[2]/div[2]/nav/ul/li[3]/a")
try:
    top100.click()
except ElementNotInteractableException:
    pass

In [168]:
Song = []
Artist = []
Lrank = []
Prank = []
Board = []

In [172]:
for i in range(1,101):  
    
    try:
        song= driver.find_elements_by_xpath(f"//span[@class='chart-element__information__song text--truncate color--primary']")
        for i in song:
            Song.append(i.text)
    except NoSuchElementException:
        Song.append('-')
        
for i in range(1,101):  
    
    try:
        artist= driver.find_elements_by_xpath(f"//span[@class='chart-element__information__artist text--truncate color--secondary']")
        for i in artist:
            Artist.append(i.text)
    except NoSuchElementException:
        Artist.append('-')
        
for i in range(1,101):  
    
    try:
        lrank= driver.find_elements_by_xpath(f"//span[@class='chart-element__meta text--center color--secondary text--last']")
        for i in lrank:
            Lrank.append(i.text)
    except NoSuchElementException:
        Lrank.append('-')

In [170]:
Lrank

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 ...]

In [160]:
for i in range(1,101):
    try:
        song = driver.find_elements_by_xpath(f"//span[@class='chart-element__information__song text--truncate color--primary']")
        Song.append(song.text)
    except NoSuchElementException:
        Song.append("-")
        
for i in range(1,101):
    try:
        artist = driver.find_elements_by_xpath(f"//span[@class='chart-element__information__artist text--truncate color--secondary']")
        Artist.append(artist.text)
    except NoSuchElementException:
        Artist.append("-")
        
for i in range(1,101):
    try:
        lrank = driver.find_elements_by_xpath(f"//div[@class='chart-element__meta text--center color--secondary text--last']")
        Lrank.append(lrank.text)
    except NoSuchElementException:
        Lrank.append("-")

for i in range(1,101):
    try:
        prank = driver.find_elements_by_xpath(f"//div[@class='chart-element__meta text--center color--secondary text--peak']")
        Prank.append(prank.text)
    except NoSuchElementException:
        Prank.append("-")

for i in range(1,101):
    try:
        board = driver.find_elements_by_xpath(f"//div[@class='chart-element__meta text--center color--secondary text--week']")
        Board.append(board.text)
    except NoSuchElementException:
        Board.append("-")

AttributeError: 'list' object has no attribute 'text'

In [143]:
Top100=pd.DataFrame({})
Top100['Song Name']=Song
Top100['Artist Name']=Artist
Top100['Last Week Rank']=Lrank
Top100['Peak Rank']=Prank
Top100['Weeks on Board']=Board
Top100

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks on Board
0,Stay,The Kid LAROI & Justin Bieber,2,1,13
1,Stay,The Kid LAROI & Justin Bieber,2,1,13
2,Stay,The Kid LAROI & Justin Bieber,2,1,13
3,Stay,The Kid LAROI & Justin Bieber,2,1,13
4,Stay,The Kid LAROI & Justin Bieber,2,1,13
...,...,...,...,...,...
95,Stay,The Kid LAROI & Justin Bieber,2,1,13
96,Stay,The Kid LAROI & Justin Bieber,2,1,13
97,Stay,The Kid LAROI & Justin Bieber,2,1,13
98,Stay,The Kid LAROI & Justin Bieber,2,1,13
99,Stay,The Kid LAROI & Justin Bieber,2,1,13

In [151]:
url =  'https://www.billboard.com/'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [152]:

top100_btn=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/nav/ul/li[3]/a") #hot100 button
try:
    top100_btn.click()#click explore button
except ElementNotInteractableException:
    pass

In [153]:

Song = []
Artist = []
Lastweek = []
Peak = []
Weeks = []

In [154]:
for i in range(1,110):
    try:
        Song_tag = driver.find_element_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li[{i}]/button/span[2]/span[1]")
        Song.append(Song_tag.text)
    except NoSuchElementException:
        Song.append("-")
        
for i in range(1,110):
    try:
        Artist_tag = driver.find_element_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li[{i}]/button/span[2]/span[2]")
        Artist.append(Artist_tag.text)
    except NoSuchElementException:
        Artist.append("-")
        
for i in range(1,110):
    try:
        Lastweek_tag = driver.find_element_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li[{i}]/button/span[2]/span[3]/span[1]")
        Lastweek.append(Lastweek_tag.text.replace("LW",""))
    except NoSuchElementException:
        Lastweek.append("-")

for i in range(1,110):
    try:
        Peak_tag = driver.find_element_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li[{i}]/button/span[2]/span[3]/span[2]")
        Peak.append(Peak_tag.text.replace("Pk",""))
    except NoSuchElementException:
        Peak.append("-")

for i in range(1,110):
    try:
        Weeks_tag = driver.find_element_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li[{i}]/button/span[2]/span[3]/span[3]")
        Weeks.append(Weeks_tag.text.replace("WoC",""))
    except NoSuchElementException:
        Weeks.append("-")

In [155]:
Top100 = {'Song name': Song,'Artist name':Artist,'Last week rank':Lastweek,'Peak rank':Peak,'Weeks on board':Weeks}

Top100 = pd.DataFrame(Top100)

Top100

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Stay,The Kid LAROI & Justin Bieber,,,
1,Industry Baby,Lil Nas X & Jack Harlow,,,
2,Fancy Like,Walker Hayes,,,
3,Way 2 Sexy,Drake Featuring Future & Young Thug,,,
4,Bad Habits,Ed Sheeran,,,
...,...,...,...,...,...
104,Esta Danada,Ivan Cornejo,,,
105,Whiskey And Rain,Michael Ray,,,
106,TSU,Drake,,,
107,Love All,Drake Featuring JAY-Z,,,
108,No Where,YoungBoy Never Broke Again,,,

## 7. Scrape the details of Data science recruiters from https://www.naukri.com/

`You have to find the following details:`
- A) Name
- B) Designation
- C) Company
- D) Skills they hire for
- E) Location

Note:- From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [173]:

url =  'https://www.naukri.com/'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [175]:
recruit_btn=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div")
try:
    recruit_btn.click()
except ElementNotInteractableException:
    pass
driver.switch_to.window(driver.window_handles[1])

In [176]:
jobsearch = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
jobsearch

In [177]:
jobsearch.send_keys("Data science")

In [178]:
srchbtn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
srchbtn.click()

In [179]:
Name = []
Designation = []
Company = []
Skills = []

In [180]:
Name_tag = driver.find_elements_by_xpath("//a[@class='ellipsis']/span")
Designation_tag = driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
Company_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
Skills_tag = driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
Location_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/span/small")

In [181]:
for n in Name_tag:
    try:
        Name.append(n.text)
    except NoSuchElementException:
        Name.append("-")
for d in Designation_tag:
    try:
        Designation.append(d.text)
    except NoSuchElementException:
        Designation.append("-")


for c in Company_tag:
    try:
        Company.append(c.text)
    except NoSuchElementException:
        Company.append("-")


for s in Skills_tag:
    try:
        Skills.append(s.text)
    except NoSuchElementException:
        Skills.append("-")

In [182]:
nameurl = []

In [183]:
name_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")

In [184]:
for r in name_tag:
    try:
        nameurl.append(r.get_attribute("href"))
    except NoSuchElementException:
        nameurl.append("-")

In [185]:
Location = []

In [186]:
for i in nameurl:
    driver.get(i)
    time.sleep(5)
    try:   
        Location_tag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")
        Location.append(Location_tag.text)
    except NoSuchElementException:
        Location.append('-')

In [187]:
jobs = {'Name': Name,'Designation':Designation,'Company':Company,'Skills they hire for':Skills,'Location':Location}

jobsDF = pd.DataFrame(jobs)

jobsDF

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Hyderabad / Secunderabad
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
16,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
18,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
30,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,Ghaziabad
35,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
36,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
37,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
38,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
43,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
46,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
48,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
49,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai

## 8. Scrape the details of Highest selling novels from  https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

`You have to find the following details:`
- A) Book name
- B) Author name
- C) Volumes sold
- D) Publisher
- E) Genre

In [188]:
url =  ' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [189]:
Book= []
Author = []
Volumes = []
Publisher = []
Genre = []

In [190]:
for i in range(1,101):
    try:
        Book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")
        Book.append(Book_tag.text)
    except NoSuchElementException:
        Book.append("-")
        
for i in range(1,101):
    try:
        Author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")
        Author.append(Author_tag.text)
    except NoSuchElementException:
        Author.append("-")
        
for i in range(1,101):
    try:
        Volumes_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")
        Volumes.append(Volumes_tag.text)
    except NoSuchElementException:
        Volumes.append("-")

for i in range(1,101):
    try:
        Publisher_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")
        Publisher.append(Publisher_tag.text)
    except NoSuchElementException:
        Publisher.append("-")

for i in range(1,101):
    try:
        Genre_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")
        Genre.append(Genre_tag.text)
    except NoSuchElementException:
        Genre.append("-")

In [191]:
Top100Books = {'Book name': Book,'Author name':Author,'Volumes sold':Volumes,'Publisher':Publisher,'Genre':Genre}

Top100BooksDF = pd.DataFrame(Top100Books)

Top100BooksDF

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## 9. Scrape the details most watched tv series of all time from https://www.imdb.com/list/ls095964455/

`You have to find the following details:`
- A) Name
- B) Year span
- C) Genre
- D) Run time
- E) Ratings
- F) Votes

In [192]:
url =  'https://www.imdb.com/list/ls095964455/'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [193]:
Name = []
Year = []
Genre = []
Runtime = []
Ratings = []
Votes = []

In [194]:

for i in range(1,101):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
        
for i in range(1,101):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")
        
for i in range(1,101):
    try:
        Genre_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]")
        Genre.append(Genre_tag.text)
    except NoSuchElementException:
        Genre.append("-")

for i in range(1,101):
    try:
        Runtime_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]")
        Runtime.append(Runtime_tag.text)
    except NoSuchElementException:
        Runtime.append("-")

for i in range(1,101):
    try:
        Ratings_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]")
        Ratings.append(Ratings_tag.text)
    except NoSuchElementException:
        Ratings.append("-")
for i in range(1,101):
    try:
        Votes_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[4]/span[2]")
        Votes.append(Votes_tag.text)
    except NoSuchElementException:
        Votes.append("-")

In [195]:
Top100shows = {'Name': Name,'Year span':Year,'Genre':Genre,'Run time':Runtime,'Ratings':Ratings,'Votes':Votes}

Top100showssDF = pd.DataFrame(Top100shows)

Top100showssDF

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,884,117"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"917,315"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"905,385"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"271,133"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"231,483"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,938"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,816"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"177,573"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,960"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"204,629"

## 10. Details of Datasets from UCI machine learning repositories https://archive.ics.uci.edu/
 
`You have to find the following details:`
- A) Dataset name
- B) Data type
- C) Task
- D) Attribute type
- E) No of instances
- F) No of attribute
- G) Year

Note:- from the home page you have to go to the Show All Dataset page through code

In [196]:
url =  'https://archive.ics.uci.edu/'
driver = webdriver.Chrome(r'C:\Users\hifzu\Downloads\chromedriver.exe')
driver.get(url)

In [197]:
dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') 
try:
    dtbtn.click() 
except ElementNotInteractableException:
    pass

In [198]:
Name = []
Datatype = []
Task = []
Attribute = []
Instances = []
Attribute_no = []
Year = []

In [199]:
for i in range(1,590):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
        
for i in range(1,590):
    try:
        Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
        Datatype.append(Datatype_tag.text)
    except NoSuchElementException:
        Datatype.append("-")
        
for i in range(1,590):
    try:
        Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
        Task.append(Task_tag.text)
    except NoSuchElementException:
        Task.append("-")

for i in range(1,590):
    try:
        Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
        Attribute.append(Attribute_tag.text)
    except NoSuchElementException:
        Attribute.append("-")

for i in range(1,590):
    try:
        instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
        Instances.append(instances_tag.text)
    except NoSuchElementException:
        Instances.append("-")
for i in range(1,590):
    try:
        attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
        Attribute_no.append(attribute_no_tag.text)
    except NoSuchElementException:
        Attribute_no.append("-")
for i in range(1,590):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")

In [201]:
repositories = {'Dataset name': Name,'Data type':Datatype,'Task':Task,'Attribute type':Attribute,'No of instances':Instances,'No of attribute':Attribute_no,'Year':Year}

repositoriesDF = pd.DataFrame(repositories)

repositoriesDF.drop(index = 0,inplace = True)

In [202]:
repositoriesDF

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
584,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
585,Gait Classification,Multivariate,Classification,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021